version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: keshav
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://keshav:password@postgres:5432/home
      PGRST_DB_ANON_ROLE: keshav
      PGRST_DB_SCHEMA: public
    ports:
      - "3000:3000"

